name: my_messanger
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.5 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  firebase_core: ^1.19.0
  flutter_redux: ^0.10.0
  equatable: ^2.0.3
  redux: ^5.0.0
  logger: ^1.1.0
  cloud_firestore: ^3.2.1
  json_serializable: ^6.2.0
  intl: ^0.17.0
  shared_preferences: ^2.0.15

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  build_runner: ^2.1.11

flutter:

  uses-material-design: true
